[workspace]
members = [
    "crates/silta-core",
    "crates/silta-http",
    "crates/silta-router",
    "crates/silta-runtime",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
license = "Apache-2.0"
repository = "https://github.com/silta-rs/siltars"
authors = ["Сергей Гнездилов"]

[workspace.dependencies]
silta-core = { path = "crates/silta-core", version = "0.1.0" }
silta-http = { path = "crates/silta-http", version = "0.1.0" }
silta-router = { path = "crates/silta-router", version = "0.1.0" }
silta-runtime = { path = "crates/silta-runtime", version = "0.1.0" }
anyhow = "1.0"
axum = "0.7"
serde = "1.0"
serde_json = "1.0"
sqlx = { version = "0.8", default-features = false }
tokio = "1.40"
