[package]
name = "silta-router"
description = "Router abstractions for Silta application descriptions."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
silta-core.workspace = true
